# Generated by Django 5.2.4 on 2025-08-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tmdb_id",
                    models.IntegerField(help_text="TMDb genre ID", unique=True),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tmdb_id",
                    models.IntegerField(help_text="TMDb movie ID", unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("original_title", models.CharField(blank=True, max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "runtime",
                    models.IntegerField(
                        blank=True, help_text="Runtime in minutes", null=True
                    ),
                ),
                (
                    "vote_average",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("vote_count", models.IntegerField(default=0)),
                (
                    "popularity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("poster_path", models.CharField(blank=True, max_length=255)),
                ("backdrop_path", models.CharField(blank=True, max_length=255)),
                ("adult", models.BooleanField(default=False)),
                ("video", models.BooleanField(default=False)),
                ("original_language", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-popularity", "-vote_average"],
            },
        ),
        migrations.CreateModel(
            name="MovieGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_genres",
                        to="movies.genre",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_genres",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "unique_together": {("movie", "genre")},
            },
        ),
    ]
